version: "3.8"

services:
  app:
    build: ./
    container_name: apiserver
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    
  migrate:
    image: migrate/migrate
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./platform/migrations:/migrations
    command:
      ["-path", "/migrations", "-database",  "postgres://postgres:password@database:5432/postgres?sslmode=disable", "up"]


volumes:
  postgres-db: